# fly.toml file generated for tzo-memos on 2023-02-15T15:11:29-07:00

app = "tzo-memos"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DB_PATH = "/var/opt/memos/memos_prod.db"
  LITESTREAM_REPLICA_BUCKET = "memos-db-backup"
  LITESTREAM_REPLICA_ENDPOINT = "s3.us-west-001.backblazeb2.com"
  LITESTREAM_REPLICA_PATH = "memos_prod.db"

[build]
  image = "hu3rror/memos-fly:latest"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  source = "memos_data"
  destination = "/var/opt/memos"

[[services]]
  http_checks = []
  internal_port = 5230
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
